### ISSUE TITLE
New API Doc - Site Parity Issue : Missing request/response payloads

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#13]
## Missing example payloads
Listing the below links where examples are missing

- http://docs-api.opsramp.com.s3-website-us-east-1.amazonaws.com/api/tenancy-access-controls/tenants-tenantid-users-userid-action/ Vs https://docs.opsramp.com/api/tenancy-access-controls/users-activate-user-post/
-  https://docs.opsramp.com/api/resource-management/resources-search-get/ Versus http://docs-api.opsramp.com.s3-website-us-east-1.amazonaws.com/api/resource-management/tenants-tenantid-resources-search/ 
- Missed SSO type of payload: https://docs.opsramp.com/api/integrations/sso-integration-update-installed-post/

### SSO missing payload examples
-  GET example for SSO needs to be added as below:
   - https://docs.opsramp.com/api/integrations/sso-integration-installed-get/
-  DELETE example (Uninstall) for SSO needs to be added as below:
  - https://docs.opsramp.com/api/integrations/sso-integration-uninstall-installed-delete/
-  Update example ( modify the URL link ) for SSO needs to be added as below:
   - https://docs.opsramp.com/api/integrations/sso-integration-update-installed-post/

**Comment by rshera01** [comment]
![image](https://user-images.githubusercontent.com/8282607/107935532-85350c80-6fa7-11eb-85e9-0a21e519dcdc.png)
One of the example payloads added.
api/integrations/tenants-tenantid-integrations-installed-installedintgid.yaml

**Comment by mwaterous** [comment]
All example payloads should be rendering, can you confirm if there's still an issue here and if so provide examples from http://docs-staging.opsramp.com.s3-website.us-east-2.amazonaws.com/api/ (docs-api website has been discontinued).

**Comment by mwaterous** [comment]
Closing this issue, please re-open if problem persists.
