### ISSUE TITLE
New API Doc-Site Parity Issue : Missing APIs

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#15]
- See these example pages
   API's links
  - https://docs.opsramp.com/api/resource-management/synthetics-collector-publiclocations-get/
  - https://docs.opsramp.com/api/resource-management/synthetics-collector-privatelocations-get/
  - https://docs.opsramp.com/api/tickets/ticket-notes-note-delete/
  - https://docs.opsramp.com/api/tenancy-access-controls/clients-resource-types-cloud-get/
  - https://docs.opsramp.com/api/tenancy-access-controls/custom-branding-get/
  - https://docs.opsramp.com/api/monitoring/monitoring-metric-get/

**Comment by geneopsramp** [comment]
All have been added to the spec except for /custom-branding-get. Will be added soon.

**Comment by geneopsramp** [comment]
Endpoints added.
