### ISSUE TITLE
HTML rendering from YAML of multi-line text failed in a parameters: in:query section.

### ISSUE THREAD

**Issue by geneopsramp** [opsramp/openapi-specs#18]
(Latest API yaml)
In tenants-tenantid-timeboundrequests-search.yaml, I moved all of 'description: |-' and associated text block to parameters: > in: query > name: queryString.

On rendering to HTML, the builder did not handle multi-line or Markdown. No errors reported.

Not necessarily a bug because we probably don't want to do this anyway, but it might be something to look into. Feel free to reject.

**Comment by mwaterous** [comment]
On rendering the descriptions for the query parameters? Presently the theme does not render markdown in the parameter description fields (only in endpoint and request method descriptions) as there is some concern it could be improperly used and the parameter displays should strive to be consistent and normalized. There may be some use cases where bold, italic, or line breaks are desired, however, so it could be added if/when we run into that situation.

**Comment by geneopsramp** [comment]
While it might be a tall order, I would think that the tool should be kind of dumb and support everything that's legal in the OpenAPI spec syntax. Constraints on the user are enforced by process and policy. You see the same thing in the DITA world where the full syntactic expression is available to the writer but needs to be limited to avoid a mess or to support a particular corporate standard. XML editors like Oxygen provide configuration settings to define what's legal syntax for any particular topic. It might be best to keep things flexible with late binding, letting policy and downstream tools like yaml generators and validators check for valid syntax.
Allow everything the spec allows. Misuse does not reflect on the tool.

**Comment by mwaterous** [comment]
> While it might be a tall order, I would think that the tool should be kind of dumb and support everything that's legal in the OpenAPI spec syntax. 

This sounds a lot like over-engineering;
-  We're not building a tool for the general public, we're building a proprietary tool for a single purpose. It will be much easier to maintain and evolve that tool if we avoid unnecessary complexity.
-  We are limited by the fact that most of the processing is being done within a template language. To create a tool that not only understands but knows how to manipulate every aspect of a specification that we ourselves do not maintain is a very tall order. We would need to abandon our present implementation and approach such an endeavor from another angle entirely.

My last argument is subjective, but it comes from decades of doing this. Regardless of established policy, if you give people the option to do it wrong, _they will_, whether intentionally or through misunderstanding. We lose nothing by setting constraints in the tool that ensure a consistent experience. Such a policy can be managed from a single point of reference, while the other approach requires monitoring many possible sources for policy infractions.

**Comment by geneopsramp** [comment]
That was my approach, too, when I used to do these kinds of things. Prevent the user from injuring themselves too badly and enforce the abstractions I thought were important. They didn't like it much back then, either, but it did make life better for all in the long run.
It will be interesting to see how the developers take to this after the doc team stops carrying water for them. That will be the real test.
