### ISSUE TITLE
queryString variables not rendered

### ISSUE THREAD

**Issue by geneopsramp** [opsramp/openapi-specs#19]
/openapi-specs/v2/agents-gateways/tenants-tenantid-managementprofiles-search.yaml

queryString variables not rendered with or without 'description' field.

**Comment by geneopsramp** [comment]
See opsramp/docs-theme issue #20 (filed in wrong repository) for variant of this issue.

**Comment by mwaterous** [comment]
Please confirm what isn't being rendered? The query parameters are being rendered as far as I can tell:

<img width="849" alt="Screen Shot 2021-03-01 at 3 32 12 PM" src="https://user-images.githubusercontent.com/6832116/109567997-7c623180-7aa3-11eb-885e-4bb16ab85a36.png">
