### ISSUE TITLE
Change to API introductory content requires change to ignore on build

### ISSUE THREAD

**Issue by geneopsramp** [opsramp/openapi-specs#25]
- deleted docs/content/api/about

- added docs/content/api/api-getting-started
        index.md
	getting-started.md
	getting-started-examples.md

- added docs/content/api/api-user-guide
        index.md
	resource-index-and-summary.md
	user-guide.md

Causes `git status` to report deleted files.
Let me know if you need more info.

**Comment by mwaterous** [comment]
Whoops, looks like I wiped your Guides in opsramp/docs@b3b31c678dbf86f5b5e1d74e93caa5d9a63aed88

This is fixed in opsramp/docs@5e4d6091015f94e662f601f3d1d5bde062f7bd5a
