### ISSUE TITLE
Agent-Gateway APIs

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#27]
Hi Mark,
We need to distinguish the Gateway and Agent APIs in separate sub headings. Currently the endpoints are mixed up and hard to classify.
Here are the endpoint for the Gateway APIs
![API documentation corrections](https://user-images.githubusercontent.com/8282607/111944211-1ba3a300-8afd-11eb-8006-bfa0f8cc39ad.png)

Further, the gateway endpoints need to be in order as below which best explains how the APIs can be used by users. The base URL is also different

Here is the base URL which is specific to client infrastructure where the gateway is deployed, 
We need to correct the APIs target as https://<GatewayIPAddress>:5480 for the below APIs.  Eg: https://172.26.1.244:5480/api/v2/apiTokenGen.

Here is the order of APIs to be put in.

     Generate gateway access token
     Gets gateway information
     Get status, start and stop application services
     Gets gateway timezone information
     Set gateway timezone
     Gets gateway NTP details
     Manually set gateway NTP date and time
     Start and stop gateway NTP service
     Synchronize NTP servers time
    Update gateway NTP server IP addresses
     Gets gateway NGINX status and restart service
     Configure gateway external proxy connection
     Register gateway
     Restart network service
     Set static route configuration
     Specifies gateway network settings
     Turn Squid proxy service on and off

**Comment by maheshramachandran** [comment]
@rsheshu : This is not an issue for @mwaterous to fix. We use the issues list in GitHub for site related issues - not spec related issues. Please create a separate JIRA ticket to track this spec related issue.
