### ISSUE TITLE
VMWare API documentation missing in the Production API doc Build

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#28]
Hi Mark,
We cannot see the VMWare API documentation https://docs.opsramp.com/api/integrations/
Here is the commit reference  https://github.com/opsramp/openapi-specs/commit/a66d1031504f8d430e978560cc4d637996434499

Is there a way now we can put use this YAML file to the documentation coming up in the current production documentation
Thanks,
-Shesha

![image](https://user-images.githubusercontent.com/8282607/113338759-2bb25280-9347-11eb-8ed2-dbcd0fa7e4e1.png)

**Comment by mwaterous** [comment]
New API content isn't currently being built on docs. I'm going to merge the new build in to production and set up a trigger so that any changes pushed to the new `production` branch of this repository will trigger a rebuild. Hold tight.

**Comment by mwaterous** [comment]
Is this the one you're looking for?

http://docs.opsramp.com.s3-website.us-east-2.amazonaws.com/api/integrations/tenants-tenantid-integrations-install-vmware/
