### ISSUE TITLE
rewire internal api site to source from develop branch instead of main branch

### ISSUE THREAD

**Issue by maheshramachandran** [opsramp/openapi-specs#33]
Mark: We discussed this. The internal API site (http://docs-internal.opsramp.com.s3-website-us-east-1.amazonaws.com/api/) needs to take .YAML files from the developer branch (https://github.com/opsramp/openapi-specs/tree/develop/v2).

**Comment by mwaterous** [comment]
Yep, sorry for the slow implementation. I've updated the build pipeline on Buddy to designate the develop branch as the source. Triggered a new build as well.

**Comment by maheshramachandran** [comment]
@mwaterous : Based on our meeting Tuesday, I believe this is done. Can we close this issue?
