### ISSUE TITLE
API docs should clearly indicate internal apis as such

### ISSUE THREAD

**Issue by maheshramachandran** [opsramp/openapi-specs#34]
Mark: We've discussed this. APIs tagged as internal should be clearly indicated in the generated API docs.

**Comment by mwaterous** [comment]
Understood, I have the code locally but I'm still not seeing any endpoints/path tagged as internal in the OpenAPI repo. Are there any samples you can point me to?

**Comment by maheshramachandran** [comment]
Mark: For now, can  you add a new hypothetical internal API and tag it as internal. You can just copy one of the existing API - modify its spec slightly and mark it as internal - and test your implementation.

After this, @rshera01 will be transcribing our internal APIs into OpenAPI spec format - this will take a while.

Thanks.

**Comment by maheshramachandran** [comment]
Closing the issue, as it has been fixed.
