### ISSUE TITLE
Branch build not reflecting the changes

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#35]
Hi Mark,
I have created a branch 9-HF-Branch and trying to build locally. The build is not reflecting the changes.
I am not sure on the build script changes . Overall i am not able to updates specs unless validated once locally
Thanks,
-Shesha

**Comment by rshera01** [comment]
Mark , 
I am not sure what did happen. I changed opsramp-patching.v2.yaml in branch  https://github.com/opsramp/openapi-specs/tree/9-HF-Branch and tried  to build locally. 
The changes were not getting reflected I later tried in my evening  it's working now.  I thought there might be build updates so created this issue.
Let me observe for one more day  and will close the issue.

**Comment by rshera01** [comment]
Hi Mark,
I tried to push some changes in main . Getting the pipeline error
![image](https://user-images.githubusercontent.com/8282607/117142750-b1ee0880-adcd-11eb-83b8-0c0af9830542.png)

Please check.

**Comment by maheshramachandran** [comment]
@rsheshu : if you are not seeing this any more - can you please close this issue?

**Comment by rshera01** [comment]
Production site is not building and triggered build has failed.
