### ISSUE TITLE
docker based api site build not working

### ISSUE THREAD

**Issue by maheshramachandran** [opsramp/openapi-specs#36]
Mark:

I tried your updated instructions (pasted below). I cloned the openapi-specs repo, checked out branch develop and ran your instructions. npm failed within the container. See attached screenshots.

_I put together a new image and updated the docker compose._

_Try pulling in the latest changes from the develop branch. You will have to build the container first, it's not pushed to the repository yet._

_From within the repo, run:_

_docker build . -t mwaterous/hugo-docker_
_docker compose up_

_See if that works._

**Comment by maheshramachandran** [comment]
![apidocs-build-error-1](https://user-images.githubusercontent.com/6510255/117365069-9c331e80-ae73-11eb-970e-f0f350185af5.png)

![apidocs-build-error-2](https://user-images.githubusercontent.com/6510255/117365093-a6551d00-ae73-11eb-8a1e-812664e41c4d.png)

![apidocs-build-error-3](https://user-images.githubusercontent.com/6510255/117365110-afde8500-ae73-11eb-8e68-d29ea8328aea.png)

**Comment by mwaterous** [comment]
Maybe I generated the lockfile prior to running the docker container.

The deleting package-lock.json, then running `docker compose up` and see if it works if it generates its own lockfile

**Comment by maheshramachandran** [comment]
FYI - I tried to build the site directly from build.js and hugo - see the error I get below.

![apidocs-build-error-5](https://user-images.githubusercontent.com/6510255/117366266-5a0adc80-ae75-11eb-98d8-89ec19096c20.png)

**Comment by maheshramachandran** [comment]
At this point, I'm stuck - unable to do make any updates to OpenAPI specs.

**Comment by maheshramachandran** [comment]
@mwaterous closing this ticket - since - as we discussed yesterday - we are not doing docker based tool for now.
