### ISSUE TITLE
local build steps are totally broken - completely blocked

### ISSUE THREAD

**Issue by maheshramachandran** [opsramp/openapi-specs#37]
Mark: At this point, we are completely blocked on making any changes to the OpenAPI specs. I tried to follow the instructions in the Wiki to do a local build - verbatim as is written in this doc: https://github.com/opsramp/openapi-specs/wiki/Testing-locally-with-Hugo

See screenshots below for the errors I get.
Can you please help us get past this. No point working a new site, if we are blocked on the current site. Can we please focus 100% of our efforts on making the current site usable?

**Comment by mwaterous** [comment]
We'll probably need to work on why the dockerfile isn't working during the meeting. It works fine on this machine, and from what I understand the whole idea is that it should work the same launched from any platform.

For running without docker, try pulling the latest `develop` branch, `cd hugo`, `npm i`, and `npm run dev`.

It looks like in your second screenshot there that the modules have not been installed. Be sure `npm i` was run from within the hugo directory and that there's a `node_modules/` directory afterwards.

**Comment by maheshramachandran** [comment]
Closing this issue - since now, after our meeting yesterday - we've resolved the npm issue. Updated instructions to build the site are here:
https://github.com/opsramp/openapi-specs/wiki/Testing-locally-with-Hugo

**Comment by maheshramachandran** [comment]
Closing this issue - since now, after our meeting yesterday - we've resolved the npm issue. Updated instructions to build the site are here:
https://github.com/opsramp/openapi-specs/wiki/Testing-locally-with-Hugo
