### ISSUE TITLE
fix github reported vulnerability

### ISSUE THREAD

**Issue by maheshramachandran** [opsramp/openapi-specs#38]
@mwaterous : See this vulnerability that GitHub as flagged. Can you please fix this.
https://github.com/opsramp/openapi-specs/security/dependabot

[github-vulnerability.pdf](https://github.com/opsramp/openapi-specs/files/6468831/github-vulnerability.pdf)

**Comment by mwaterous** [comment]
Strange, it's gone now. There may have been an automated update to the package that solved it.

**Comment by mwaterous** [comment]
Closing, alert hasn't returned so I'm assuming the author has updated the package vulnerability. Will re-open if it returns.
