### ISSUE TITLE
Introducing Sub-menu in the API menu items

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#40]
Hi Mark,
Need quick help on this. I introduced a new file "opsramp-org-gateways.v2.yaml"
This is not showing up as an item in the root menu subsequently all the end-point within it are scattered without the parent item.

Please check : 
http://docs-internal.opsramp.com.s3-website-us-east-1.amazonaws.com/api/org-gateways/v2-auth-token/
I want to make this into production, once the appropriate sub-menu item is shown

Can this be looked into? let me know what needs to be done to do this:

image for reference:

![image](https://user-images.githubusercontent.com/8282607/120338489-e6dc7500-c311-11eb-8e52-965ae1c466b5.png)
thanks,
-Shesha

**Comment by mwaterous** [comment]
Fixed. This is a shortcoming of the current Hugo website, where the index file for new endpoint groups has to be manually generated for the table of contents organization to properly update. The next phase won't have this problem but for now I've pushed up a new commit with the necessary markdown file to fix the problem.
