### ISSUE TITLE
Merge with develop branch to main for production doc.

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#41]
Hi Mark,
Can we merge the develop branch committed at [commit](https://github.com/opsramp/openapi-specs/commit/1ee5486a014c77bfae4a9f83494bc67939cc09f4) to main so that it would be visible to all? Since there are some build.s changes associated. can you please merge the develop branch yaml changes to the production

Thanks,
-Shesha

**Comment by mwaterous** [comment]
Everything up to 1ee5486a014c77bfae4a9f83494bc67939cc09f4 has been merged into main.

**Comment by rshera01** [comment]
Hi Mark,
![image](https://user-images.githubusercontent.com/8282607/120651618-9cd3ca80-c49c-11eb-90ad-c9a1cfb25049.png)

We need to move this under Submenu as it was done in develop branch
Thanks,
-shesha

**Comment by rshera01** [comment]
Hi Mark,
https://docs.opsramp.com/api/agents-gateways/ntpmanualconfig/
This has been marked as internal. This should not be shown in the production documentation.

see the internal tagging done in yaml
  /api/v2/ntpmanualconfig:
    x-internal: true

**Comment by mwaterous** [comment]
Yes, this is because that feature was added to the openapi repository for the next phase of the API site development. It was never added to the production docs repo. I'll work on updating it.

**Comment by mwaterous** [comment]
Everything should be up to speed on docs.opsramp.com now.
