### ISSUE TITLE
Production build update

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#42]
Hi Mark,

I made a commit at b1dff01 and the build has failed.  Changes as below:
1.Reverted "internal tag" the old gateway API  changes to make it public as these are supposed to be in the production now.
2.Made the "Standalone gateway" API changes to internal as this is supposed to be released after few months.

Can we make "the standalone sub-menu only visible for internal API documentation for the time being till we want to release it
Please let me if this can be facilitated.

I mistakenly made a commit of "Standalone gateway" API changes which are supposed to be done later.

Thanks,
-Shesha

**Comment by mwaterous** [comment]
I removed the org-gateways index from docs/main so that it will not appear in the table of contents.
