### ISSUE TITLE
Document the Authentication endpoint 

### ISSUE THREAD

**Issue by rshera01** [opsramp/openapi-specs#43]
Hi Mark,
We have missed the endpoint    https://{tenant-name}.api.opsramp.com/auth/oauth/token

Updated develop branch at [commit](https://github.com/opsramp/openapi-specs/commit/a34eab866c8783e4bab68b34b6af92451a80b919)

The submenu-item should be "Authentication". Can we enable this in the current documentation model?
Thanks,
-Shesha

**Comment by rshera01** [comment]
![image](https://user-images.githubusercontent.com/8282607/124717644-f3f90f00-df22-11eb-985a-8a74ea56c364.png)
![image](https://user-images.githubusercontent.com/8282607/124717665-f9565980-df22-11eb-89d2-a84e4d98d76e.png)

Hi Mark ,
I get the above errors. This I have already tried by making local changes and was getting the same errors.  There is some "TypeError" of schema. This needs to be looked in terms of code.
Thanks,
-Shesha

**Comment by mwaterous** [comment]
I didn't update the build script in the openapi repo, only the one in docs. I'll make the same updates there and let you know when that's ready for testing.

**Comment by mwaterous** [comment]
Pull down the latest two commits and give it another try, let me know if that works for you!

**Comment by rshera01** [comment]
This is working .closing it now. Need to merge with main branch
