### ISSUE TITLE
Status property type should be string

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#49]
```bash
 1640:31  error  oas3-valid-oas-content-example  `status` property type should be string  paths./api/v2/tenants/{tenantId}/managementProfiles/{profileId}.post.requestBody.content.application/json.examples.enable-disable-services.value.services[0].status
 1901:37  error  oas3-valid-oas-content-example  `status` property type should be string  paths./api/v2/tenants/{tenantId}/managementProfiles/search.get.responses[200].content.application/json.examples.serviceStatus-all.value.results[1].services[0].status
 1948:37  error  oas3-valid-oas-content-example  `status` property type should be string  paths./api/v2/tenants/{tenantId}/managementProfiles/search.get.responses[200].content.application/json.examples.registered-true-gw-profiles.value.results[0].services[0].status
```

The first occurrence here is demonstrating a boolean response:
https://github.com/opsramp/openapi-specs/blob/6b8de67eb954c90f418483425f8a3f19403c78c5/v2/opsramp-agents-gateways.v2.yaml#L1640

The definition states it should be a string:
https://github.com/opsramp/openapi-specs/blob/6b8de67eb954c90f418483425f8a3f19403c78c5/v2/opsramp-agents-gateways.v2.yaml#L1617

Either the definition should be updated to reflect a boolean response, or the example should be updated to represent the response as a string.

**Comment by rshera01** [comment]
Updated and fixed. All the OpenAPI specs do not have any linting errors now
