### ISSUE TITLE
installTimeout in automation should be boolean

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#52]
installTimeout is described as being a boolean:
https://github.com/opsramp/openapi-specs/blob/6b8de67eb954c90f418483425f8a3f19403c78c5/v2/opsramp-automation.v2.yaml#L1749

Provided example shows an integer:
https://github.com/opsramp/openapi-specs/blob/6b8de67eb954c90f418483425f8a3f19403c78c5/v2/opsramp-automation.v2.yaml#L1787

**Comment by rshera01** [comment]
Cleaned up in the specs cleanup
