### ISSUE TITLE
rbaScriptParameter defines parameters as an object, provided example shows array

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#53]
Definition of `parameters` is here:
https://github.com/opsramp/openapi-specs/blob/6b8de67eb954c90f418483425f8a3f19403c78c5/v2/opsramp-automation.v2.yaml#L2048

Example provided returns an array of objects here:
https://github.com/opsramp/openapi-specs/blob/6b8de67eb954c90f418483425f8a3f19403c78c5/v2/opsramp-automation.v2.yaml#L1691

**Comment by rshera01** [comment]
Cleaned up and fixed. These are Model errors since initial days
