### ISSUE TITLE
Path shows {articleId} but references {resourceId} 

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#54]
The path as seen here:
https://github.com/opsramp/openapi-specs/blob/6b8de67eb954c90f418483425f8a3f19403c78c5/v2/opsramp-knowledge-base.v2.yaml#L1501

This endpoint is showing `articleId` in the path, but references `resourceId` in the parameters. Need to update the path or the reference.

**Comment by rshera01** [comment]
Fixed http://docs-internal.opsramp.com.s3-website-us-east-1.amazonaws.com/api/knowledge-base/tenants-tenantid-kb-article-articleid-delete/
