### ISSUE TITLE
external api docs site looks different and worse than internal api docs site

### ISSUE THREAD

**Issue by maheshramachandran** [opsramp/openapi-specs#59]
See the two API docs sites below (see screenshots attached):
1) https://docs.opsramp.com/api/
2) http://docs-internal.opsramp.com.s3-website-us-east-1.amazonaws.com/api/

The external customer facing site looks different and worse than the internal API site. Please fix.

**Comment by maheshramachandran** [comment]
![internal-api-docs](https://user-images.githubusercontent.com/6510255/127523106-00b59dad-5661-4407-85ce-284989250ec8.png)

![external-api-docs](https://user-images.githubusercontent.com/6510255/127523125-5c08eb63-1de4-4962-ac1a-76041620fafe.png)

**Comment by mwaterous** [comment]
The customer facing site has been fixed so that "Get OAuth 2.0 Access Token" appears under "Authentication" as expected.
