### ISSUE TITLE
Remove all (optional) descriptions before launch

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#63]
A reminder that (optional) is not needed, since OpenAPI has a required field that should be used where necessary.

**Comment by rshera01** [comment]
This is a legacy carrier over during the conversion while converting to OpenAPI Specs from MD files. These needs a scrutiny and cleanup for almost all the endpoints which has this type representation. However this shouldn't be a rendering issue.  
These is more of a cleanup of the content and its representation.

**Comment by mwaterous** [comment]
It's not a rendering issue, but it does cause inconsistent documentation. I self assigned this so you don't need to worry about it, I'll go through and clean it up before launch.
