### ISSUE TITLE
Confirm use of query string object for patching endpoint

### ISSUE THREAD

**Issue by mwaterous** [opsramp/openapi-specs#64]
The endpoint:
`/api/v2/tenants/{tenantId}/patches`

Starts here:
https://github.com/opsramp/openapi-specs/blob/5ca943366fe3e717050f9ce0ea9df001339c5e76/v2/opsramp-patching.v2.yaml#L1861

Parameter in question:
https://github.com/opsramp/openapi-specs/blob/5ca943366fe3e717050f9ce0ea9df001339c5e76/v2/opsramp-patching.v2.yaml#L1936

This seems to imply a request would look similar to:

`/api/v2/tenants/{tenantId}/patches?pageNo=1&pageSize=100&queryString[name]=TheName&querystring[uid]=00101&queryString[startReleaseDate]=2018-08-19T08%3A30%3A20%2B0000`

Can you confirm what a properly formatted request for this endpoint would look like?

**Comment by rshera01** [comment]
We need to generalize such Query request in the introduction and Gene is working on this . We have an internal documentation update for the same . DOC-2813.

**Comment by mwaterous** [comment]
I'm not sure this is the same issue but I could be mistaken - this isn't the wording or description that needs an update, it's the representation of the payload in the OpenAPI spec. It's not related to the other endpoints that have "Notes" in the main description.

**Comment by rshera01** [comment]
OpsRamp Query Search is not working as an endpoint search with "=" and query param "values"

A typical Search endpoint is operating like this below:

`https://api.opsramp.com/api/v2/tenants/client_593972/alerts/search?pageNo=1&pageSize=2&isDescendingOrder=true&sortName=ts&queryString=clientIds:client_1,client_2+startDate:2015-06-10T05:39:51 0000+endDate:2015-08-10T05:39:51 0000+priority:P0,P1+states:CRITICAL,OK+uniqueId:10+deviceStatus:manage+resourceType:REDSHIFT+resourceIds:DEV0000015753,148e892d-84ce-496c-a123-f91e1a8a3f7d+actions:closed,ticketed+alertTypes:agent,obsolete+metrics:zenoss,xenapp+duration:7+alertTimeBase:updated+ticketId:INC0000000001`

I was referring the needs to be defined as API introduction topic  in general as the above format is constant for all search queries.

**Comment by mwaterous** [comment]
Okay, can we leave this open until it's resolved though? The ticket is in reference to this:

https://github.com/opsramp/openapi-specs/blob/5ca943366fe3e717050f9ce0ea9df001339c5e76/v2/opsramp-patching.v2.yaml#L1936

Which is defining an object as part of the query string payload, an object called `queryString`. This doesn't match up with how OpenAPI says query string objects should be defined and as such will not render properly unless I adjust the property component to compensate for it.

**Comment by rshera01** [comment]
I accidentally closed it . reopening it

**Comment by rshera01** [comment]
[cf66780 ](https://github.com/opsramp/openapi-specs/commit/cf66780b6d2d64c66e87c99ac992c91185b844f9)This is the committed changed for the patching endpoint.
We can close this. As such in general Query related endpoints needs to have detailing in intro section.

**Comment by rshera01** [comment]
This done and update. This was a conversion issue and content related only. This is not at all related to any schema related issue.
updated the internal site : http://docs-internal.opsramp.com.s3-website-us-east-1.amazonaws.com/api/patching/tenants-tenantid-patches/

**Comment by rshera01** [comment]
Closing the issue
